version: "3.8"
services:
  nginx:
    image: nginx:mainline-alpine
    ports:
      - "5000:80"
    volumes:
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      args:
        NODE_ENV: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    env_file:
      - ./backend/.env

  db:
    image: mongo:4.4.8
    ports:
      - "27017:27017"
    volumes:
      - vidly:/data/db

volumes:
  vidly:
