version: "3.8"
services:
  backend:
    image: ${IMAGE}
    depends_on:
      - db
    env_file:
      - ./backend/.env
    restart: unless-stopped
    command: npm run start

  nginx:
    image: nginx:mainline-alpine
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mongo:4.4.8
    ports:
      - "27017:27017"
    volumes:
      - vidly:/data/db
    restart: unless-stopped

volumes:
  vidly:
