def gv
def IMAGE_NAME
pipeline {
    agent any
    tools {
        nodejs "nodejs"
    }
    
    stages {
        stage('init'){
            steps {
                script {
                    gv = load "script.groovy"
                }
            }
        }

        stage('versioning') {
            steps {
               script{
                   def tag = VersionNumber (versionNumberString: '${BUILD_DATE_FORMATTED, "yyyyMMdd"}-develop-${BUILDS_TODAY}')
                   IMAGE_NAME="puram/tour:${tag}"
               }
            }
        }

        stage('cloning-app'){
            steps {
                script {
                    gv.cloneApp()
                }
            }
        }

        stage('building-image'){
            steps {
                script {
                    gv.buildImage(IMAGE_NAME)
                }
            }
        }

        stage('deploying'){
            when {
                expression {
                    BRANCH_NAME == 'master'
                }
            }
            steps {
                script {
                    gv.deployApp(IMAGE_NAME)
                }
            }
        }
    }
}